CREATE TYPE PAYMENT_STATUS
    AS ENUM('Total', 'Parcial', 'Excedente');

CREATE CAST(VARCHAR AS PAYMENT_STATUS) WITH INOUT AS IMPLICIT;

CREATE TABLE SELLER(
    SELLER_ID BIGSERIAL PRIMARY KEY,
    SELLER_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE INVOICE(
    INVOICE_ID BIGSERIAL PRIMARY KEY,
    INVOICE_TOTAL NUMERIC(10, 2) NOT NULL,
    INVOICE_DESCRIPTION VARCHAR(50) NOT NULL
);

CREATE TABLE PAYMENT(
    PAYMENT_ID BIGSERIAL PRIMARY KEY,
    PAYMENT_AMOUNT NUMERIC(10, 2) NOT NULL,
    PAYMENT_STATUS PAYMENT_STATUS NULL,
    INVOICE_ID BIGINT NOT NULL,
    SELLER_ID BIGINT NOT NULL,
    CONSTRAINT fk_invoice FOREIGN KEY(INVOICE_ID) REFERENCES INVOICE(INVOICE_ID),
    CONSTRAINT fk_seller FOREIGN KEY(SELLER_ID) REFERENCES SELLER(SELLER_ID)
);