/* SELLERS */
INSERT INTO SELLER(SELLER_NAME)
VALUES('Anderson Bruno Novaes');

INSERT INTO SELLER(SELLER_NAME)
VALUES('Alícia Ana Dias');

INSERT INTO SELLER(SELLER_NAME)
VALUES('Guilherme Danilo Samuel Caldeira');

INSERT INTO SELLER(SELLER_NAME)
VALUES('Francisca Luna Fernandes');

INSERT INTO SELLER(SELLER_NAME)
VALUES('Raquel Elaine Barros');

/* INVOICES */
INSERT INTO INVOICE(INVOICE_TOTAL, INVOICE_DESCRIPTION)
VALUES(600.00, 'Julio e Joana Pães e Doces ME');

INSERT INTO INVOICE(INVOICE_TOTAL, INVOICE_DESCRIPTION)
VALUES(250.90, 'Andrea e Aline Alimentos Ltda');

INSERT INTO INVOICE(INVOICE_TOTAL, INVOICE_DESCRIPTION)
VALUES(8500.00, 'Yasmin e Igor Gráfica Ltda');